[2021-05-24 16:24:02,094] {taskinstance.py:669} INFO - Dependencies all met for <TaskInstance: udac_example_dag.Run_data_quality_checks 2021-05-24T23:20:13.032919+00:00 [queued]>
[2021-05-24 16:24:02,102] {taskinstance.py:669} INFO - Dependencies all met for <TaskInstance: udac_example_dag.Run_data_quality_checks 2021-05-24T23:20:13.032919+00:00 [queued]>
[2021-05-24 16:24:02,102] {taskinstance.py:879} INFO - 
--------------------------------------------------------------------------------
[2021-05-24 16:24:02,102] {taskinstance.py:880} INFO - Starting attempt 1 of 1
[2021-05-24 16:24:02,102] {taskinstance.py:881} INFO - 
--------------------------------------------------------------------------------
[2021-05-24 16:24:02,109] {taskinstance.py:900} INFO - Executing <Task(DataQualityOperator): Run_data_quality_checks> on 2021-05-24T23:20:13.032919+00:00
[2021-05-24 16:24:02,112] {standard_task_runner.py:53} INFO - Started process 98283 to run task
[2021-05-24 16:24:02,163] {logging_mixin.py:112} INFO - Running %s on host %s <TaskInstance: udac_example_dag.Run_data_quality_checks 2021-05-24T23:20:13.032919+00:00 [running]> Dylan.local
[2021-05-24 16:24:02,175] {data_quality.py:22} INFO - DataQualityOperator not implemented yet
[2021-05-24 16:24:02,179] {taskinstance.py:1065} INFO - Marking task as SUCCESS.dag_id=udac_example_dag, task_id=Run_data_quality_checks, execution_date=20210524T232013, start_date=20210524T232402, end_date=20210524T232402
[2021-05-24 16:24:12,094] {logging_mixin.py:112} INFO - [2021-05-24 16:24:12,094] {local_task_job.py:103} INFO - Task exited with return code 0
