[2021-05-24 16:35:26,455] {taskinstance.py:669} INFO - Dependencies all met for <TaskInstance: udac_example_dag.Run_data_quality_checks 2019-01-12T05:00:00+00:00 [queued]>
[2021-05-24 16:35:26,461] {taskinstance.py:669} INFO - Dependencies all met for <TaskInstance: udac_example_dag.Run_data_quality_checks 2019-01-12T05:00:00+00:00 [queued]>
[2021-05-24 16:35:26,461] {taskinstance.py:879} INFO - 
--------------------------------------------------------------------------------
[2021-05-24 16:35:26,461] {taskinstance.py:880} INFO - Starting attempt 1 of 1
[2021-05-24 16:35:26,461] {taskinstance.py:881} INFO - 
--------------------------------------------------------------------------------
[2021-05-24 16:35:26,467] {taskinstance.py:900} INFO - Executing <Task(DataQualityOperator): Run_data_quality_checks> on 2019-01-12T05:00:00+00:00
[2021-05-24 16:35:26,470] {standard_task_runner.py:53} INFO - Started process 99173 to run task
[2021-05-24 16:35:26,523] {logging_mixin.py:112} INFO - Running %s on host %s <TaskInstance: udac_example_dag.Run_data_quality_checks 2019-01-12T05:00:00+00:00 [running]> 1.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.ip6.arpa
[2021-05-24 16:35:26,538] {data_quality.py:22} INFO - DataQualityOperator not implemented yet
[2021-05-24 16:35:26,541] {taskinstance.py:1065} INFO - Marking task as SUCCESS.dag_id=udac_example_dag, task_id=Run_data_quality_checks, execution_date=20190112T050000, start_date=20210524T233526, end_date=20210524T233526
[2021-05-24 16:35:36,454] {logging_mixin.py:112} INFO - [2021-05-24 16:35:36,453] {local_task_job.py:103} INFO - Task exited with return code 0
